import { EditorialPlaybookJsonSchema } from './schemas';

export const HAIR_TRANSPLANT_PLAYBOOK_SLUG = 'transplante-capilar';

export const HAIR_TRANSPLANT_PLAYBOOK = EditorialPlaybookJsonSchema.parse({
  schema_version: 1,
  version: 1,
  vertical: 'transplante_capilar',
  positioning: 'Transplante capilar bem feito nao cria outra pessoa; recupera a melhor versao do paciente com naturalidade, seguranca, planejamento e acompanhamento.',
  audience_diagnosis: 'Pessoas considerando transplante capilar chegam com medo de dor, cicatriz, artificialidade, resultado incerto, area doadora insuficiente, preco inadequado e duvidas sobre avaliacao, pre, cirurgia e pos-operatorio.',
  core_questions: [
    'Transplante capilar doi?',
    'Vai ficar artificial?',
    'Fica cicatriz?',
    'Meu cabelo transplantado pode cair?',
    'Quanto tempo demora para ver resultado?',
    'Minha area doadora e suficiente?',
    'Qual a diferenca entre FUE, FUT e No Shave?',
    'O resultado final aparece quando?',
    'Como funciona a avaliacao?',
  ],
  voice: {
    tone: ['medico e acessivel', 'seguro sem arrogancia', 'educativo sem ser professoral', 'acolhedor', 'comercial sem sensacionalismo', 'direto e humano'],
    avoid: ['milagre', 'garantido', '100%', 'perfeito', 'sem risco', 'ultimas vagas', 'preco imperdivel', 'resultado garantido'],
  },
  editorial_pillars: [
    {
      key: 'duvidas_objecoes',
      name: 'Duvidas e objecoes',
      description: 'Responder perguntas diretas do lead com explicacao simples e CTA para avaliacao.',
      ideal_format: 'Pergunta forte + resposta curta + explicacao + CTA.',
      examples: ['Transplante capilar doi?', 'O cabelo transplantado cai?', 'Quanto tempo demora para voltar a rotina?'],
    },
    {
      key: 'mitos_verdades',
      name: 'Mitos e verdades',
      description: 'Desmontar crencas populares e fake news com correcao tecnica.',
      ideal_format: 'Mito forte + correcao tecnica + orientacao pratica.',
      examples: ['Bone causa queda?', 'Todo transplante fica artificial?', 'Raspar o cabelo fortalece os fios?'],
    },
    {
      key: 'evolucao_resultado',
      name: 'Antes e depois / evolucao',
      description: 'Mostrar evolucao de caso com carater educativo, sem prometer resultado.',
      ideal_format: 'Estagio do resultado + o que ainda evolui + ressalva de avaliacao individual.',
      examples: ['3 meses', '6 meses', '12 meses', 'linha frontal', 'coroa', 'barba'],
    },
    {
      key: 'tecnica_processo',
      name: 'Tecnica e processo',
      description: 'Explicar procedimento, FUE, planejamento, area doadora, direcao dos fios e pos-operatorio.',
      ideal_format: 'Por tras do resultado existe metodo.',
      examples: ['O que e FUE?', 'Como a hairline e planejada?', 'Como funciona o pos-operatorio?'],
    },
    {
      key: 'autoridade_bastidores',
      name: 'Autoridade medica e bastidores',
      description: 'Mostrar medico, equipe, estrutura, avaliacao, acompanhamento e rotina conectados ao beneficio do paciente.',
      ideal_format: 'Bastidor + criterio tecnico + impacto na seguranca do paciente.',
      examples: ['Marcacao da hairline', 'lavagem pos-operatoria', 'retorno de paciente'],
    },
    {
      key: 'alertas_seguranca',
      name: 'Alertas e seguranca',
      description: 'Proteger o paciente de decisoes ruins, preco baixo demais e procedimentos sem criterio.',
      ideal_format: 'Alerta sobrio + criterios objetivos + CTA para avaliacao responsavel.',
      examples: ['Cuidado com transplante so pelo preco', 'Como escolher uma clinica?', 'Por que avaliacao medica e indispensavel?'],
    },
    {
      key: 'autoestima_identificacao',
      name: 'Autoestima e identificacao',
      description: 'Conectar cabelo, identidade e confianca sem melodrama.',
      ideal_format: 'Frase de identificacao + acolhimento + solucao responsavel.',
      examples: ['Entradas afetando confianca', 'medo de parecer mais velho', 'recuperar sua versao natural'],
    },
    {
      key: 'topo_funil',
      name: 'Topo de funil',
      description: 'Conteudos leves, curiosos e compartilhaveis com orientacao util.',
      ideal_format: 'Gancho curioso + explicacao util + ponte para avaliacao.',
      examples: ['genetica materna ou paterna', 'queda depois de covid', 'sinais iniciais de calvicie'],
    },
    {
      key: 'conversao',
      name: 'Fundo de funil / conversao',
      description: 'Reduzir friccao de quem esta quase chamando no WhatsApp.',
      ideal_format: 'Explicar proximo passo + diminuir inseguranca + CTA claro.',
      examples: ['Como funciona a avaliacao?', 'O que enviar para pre-avaliacao?', 'Por que preco depende de avaliacao?'],
    },
  ],
  funnel_distribution: {
    topo: 35,
    meio: 35,
    fundo: 20,
    institucional: 10,
  },
  formats: [
    { key: 'reels_curto', name: 'Reels curto', structure: ['Hook de 1 linha', 'Resposta direta', 'Explicacao em 2 ou 3 blocos', 'Fechamento com CTA'] },
    { key: 'carrossel', name: 'Carrossel', structure: ['Capa com promessa clara', 'Problema ou mito', 'Explicacao tecnica', 'Exemplo pratico', 'Cuidados ou alerta', 'CTA'] },
    { key: 'post_unico', name: 'Post estatico', structure: ['Frase forte', 'Contexto curto', 'CTA responsavel'] },
    { key: 'legenda', name: 'Legenda', structure: ['Primeira frase forte', 'Explicacao clara', 'CTA', 'Hashtags sobrias'] },
  ],
  headline_formulas: [
    'O que ninguem te explica sobre [tema]',
    'Antes de fazer transplante capilar, entenda isso',
    'Isso pode estar impedindo seu resultado',
    'Transplante capilar nao e so colocar cabelo',
    'O erro de escolher transplante so pelo preco',
    'Com 6 meses, esse ainda nao e o resultado final',
    'Por que a linha frontal define a naturalidade?',
    'O cabelo transplantado cai?',
  ],
  ctas: {
    recommended: [
      'Agende uma avaliacao.',
      'Envie suas fotos para uma pre-avaliacao.',
      'Fale com a equipe pelo WhatsApp.',
      'Entenda qual tecnica faz sentido para o seu caso.',
      'Quer saber se voce e candidato? Comece pela avaliacao.',
    ],
    forbidden: [
      'Garanta seu resultado.',
      'Resolva sua calvicie de uma vez.',
      'Ultimas vagas.',
      'Resultado perfeito.',
      'Transplante sem risco.',
      '100% indolor.',
      'Preco imperdivel.',
    ],
  },
  compliance_rules: [
    'Manter carater educativo e linguagem sobria.',
    'Nao prometer resultado, ausencia total de dor, risco, cicatriz ou complicacoes.',
    'Nao afirmar que todos sao candidatos.',
    'Nao transformar antes/depois em promessa.',
    'Nao criar urgencia falsa.',
    'Incentivar avaliacao individual.',
    'Quando falar de procedimento, lembrar que resultado, tecnica e quantidade de foliculos dependem da area doadora e do planejamento medico.',
  ],
  quality_criteria: [
    'A headline responde uma dor real?',
    'O conteudo educa ou so enfeita?',
    'Existe promessa exagerada?',
    'Esta claro para qual etapa do funil serve?',
    'Tem CTA coerente?',
    'O paciente entende o proximo passo?',
    'O texto poderia ser falado naturalmente por um medico ou equipe da clinica?',
    'O conteudo ajuda a vender sem parecer apelativo?',
  ],
});
